# Generated by Django 5.2 on 2025-07-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
