# Generated by Django 5.2 on 2025-08-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_category_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
