# Generated by Django 5.2 on 2025-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_address_name_ru_address_name_uz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
