# Generated by Django 5.2 on 2025-07-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commons",
            "0002_district_name_ru_district_name_uz_region_name_ru_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="common",
            name="title_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="common",
            name="title_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
